version: '3.8'

services:
  client-app:
    image: "node:14"
    container_name: client-app-mercafacil
    working_dir: /home/node/app
    volumes:
      - ./project/client/:/home/node/app
    expose:
        - "3000"
    restart: always
    command: bash -c "npm i && npm run dev"
    networks:
      - mercafacil
  
  server-app:
    image: "node:14"
    container_name: server-app-mercafacil
    working_dir: /home/node/app
    volumes:
      - ./project/server/:/home/node/app
    expose:
      - "5000"
    restart: always
    command: bash -c "npm i && npm start"
    networks:
      - mercafacil

  mysql:
    image: mysql:latest
    container_name: mysql-mercafacil
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: macapa
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    networks:
      - mercafacil

  postgresql:
    image: postgres:latest
    container_name: postgresql-mercafacil
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "varejao"
    restart: always
    volumes:
      - ./postgresql-scripts:/docker-entrypoint-initdb.d
    networks:
      - mercafacil

networks:
  mercafacil:
    name: mercafacil
    driver: bridge