CREATE TABLE contacts (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR ( 200 ) NOT NULL,
	cellphone VARCHAR ( 20 ) NOT NULL
);

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	login VARCHAR ( 50 ) NOT NULL,
	password VARCHAR ( 40 ) NOT NULL,
	id_client INT NOT NULL
);
